# Generated by Django 3.2.8 on 2021-10-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_id', models.CharField(max_length=50)),
                ('api_hash', models.CharField(max_length=50)),
            ],
        ),
    ]
